name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Build status website
    runs-on: [self-hosted, Linux, X64, beast-unit]
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.43.16
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.PAT }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/status-page/__sapper__/export/
          cname: status.nomercy.tv
